require.config({  
    paths: {
    	cordova:'cordova',   
        
        angular:'ionic/js/angular/angular.min',  
        angularAnimate:'ionic/js/angular/angular-animate.min',  
        angularSanitize:'ionic/js/angular/angular-sanitize.min',  
        uiRouter:'ionic/js/angular-ui/angular-ui-router.min',  
        ngResource:'ionic/js/angular/angular-resource.min',  
  
        ionic:'ionic/js/ionic.min',  
        ionicAngular:'ionic/js/ionic-angular.min',  
        
        app:'app',
        config:'config',
        
        services:'../js/services/services',  
        factoryServices:'../js/services/factoryServices', 
        mainServices:'../js/services/mainServices', 
        timePickerService:'../js/services/timePickerService', 
        
        directives:'../js/directives/directives',
        
        baseController:'../js/controllers/baseController',
        indexController:'../js/controllers/indexController',
        guideController:'../js/controllers/guideController',
        integralController:'../js/controllers/integralController',
        showSignHistoryController:'../js/controllers/showSignHistoryController',
        buyRecordController:'../js/controllers/buyRecordController',
        buyRecordTwoController:'../js/controllers/buyRecordTwoController',
        buyRecordDetailController:'../js/controllers/buyRecordDetailController',
        rechargeController:'../js/controllers/rechargeController',
        productztController:'../js/controllers/productztController',
        productlistController:'../js/controllers/productlistController',
        searchController:'../js/controllers/searchController',
        newproductDetailController:'../js/controllers/newproductDetailController',
        productQishuController:'../js/controllers/productQishuController',
        orderdetailShareController:'../js/controllers/orderdetailShareController',
        orderShareDetailsController:'../js/controllers/orderShareDetailsController',
        userIndexController:'../js/controllers/userIndexController',
        userCardController:'../js/controllers/userCardController',
        shopnumberController:'../js/controllers/shopnumberController',
        productJisuanController:'../js/controllers/productJisuanController',
        newPublishListController:'../js/controllers/newPublishListController',
        cartController:'../js/controllers/cartController',
        orderFormController:'../js/controllers/orderFormController',
        payFinishController:'../js/controllers/payFinishController',
        myIndexController:'../js/controllers/myIndexController',
        mySetingController:'../js/controllers/mySetingController',
        accountDetailController:'../js/controllers/accountDetailController',
        userAddressController:'../js/controllers/userAddressController',
        userAddressSubmitController:'../js/controllers/userAddressSubmitController',
        userAddressSelController:'../js/controllers/userAddressSelController',
        shaidanController:'../js/controllers/shaidanController',
        cashController:'../js/controllers/cashController',
        traderPassSetController:'../js/controllers/traderPassSetController',
        newsController:'../js/controllers/newsController',
        lyController:'../js/controllers/lyController',
        aboutController:'../js/controllers/aboutController',
        mySetingSafeController:'../js/controllers/mySetingSafeController',
        logPassModController:'../js/controllers/logPassModController',
        logisticsController:'../js/controllers/logisticsController',
        myInfoController:'../js/controllers/myInfoController',
        myNicknameController:'../js/controllers/myNicknameController',
        mySexController:'../js/controllers/mySexController',
        myBirthdayController:'../js/controllers/myBirthdayController',
        myQqController:'../js/controllers/myQqController',
        myHometownController:'../js/controllers/myHometownController',
        mySignatureController:'../js/controllers/mySignatureController',
        logController:'../js/controllers/logController',
        bindingController:'../js/controllers/bindingController',
        securityCodeController:'../js/controllers/securityCodeController',
        setPasswordController:'../js/controllers/setPasswordController',
        changePasswordController:'../js/controllers/changePasswordController',
        registerController:'../js/controllers/registerController',
        registerStepTwoController:'../js/controllers/registerStepTwoController',
        registerStepThreeController:'../js/controllers/registerStepThreeController',
        logPassbackController:'../js/controllers/logPassbackController',
        commissionController:'../js/controllers/commissionController',
        rollOutController:'../js/controllers/rollOutController',
        inviteIntrController:'../js/controllers/inviteIntrController',
        customerServiceController:'../js/controllers/customerServiceController',
        userVirtualAddressSubmitController:'../js/controllers/userVirtualAddressSubmitController',
        giftController:'../js/controllers/giftController',
        mySetingSecretController:'../js/controllers/mySetingSecretController',
        integralDetailsController:'../js/controllers/integralDetailsController',
        imageTextController:'../js/controllers/imageTextController',
        proBuyDetailController:'../js/controllers/proBuyDetailController',
        winGoodsController:'../js/controllers/winGoodsController',
        luckDrawController:'../js/controllers/luckDrawController',
        winGoodsDetailController:'../js/controllers/winGoodsDetailController',
        logisticsActController:'../js/controllers/logisticsActController',
        shaidanActController:'../js/controllers/shaidanActController',
        userAddressActSelController:'../js/controllers/userAddressActSelController',
        userVirtualAddrActSubmitController:'../js/controllers/userVirtualAddrActSubmitController',
        shareListController:'../js/controllers/shareListController',
        shareDetailController:'../js/controllers/shareDetailController',
        newbieController:'../js/controllers/newbieController',
        newbieDetailController:'../js/controllers/newbieDetailController',
        newOrderFormController:'../js/controllers/newOrderFormController',
        newbieQishuController:'../js/controllers/newbieQishuController',
        noticeListController:'../js/controllers/noticeListController',
        noticeDetailController:'../js/controllers/noticeDetailController',
        gainerListController:'../js/controllers/gainerListController',
        snatchController:'../js/controllers/snatchController',
        suppleController:'../js/controllers/suppleController',
        moneygetController:'../js/controllers/moneygetController',
        gamesController:'../js/controllers/gamesController',
        controllers:'../js/controllers/controllers',
        
    },
    shim:{  
        angular : {exports : 'angular'}, 
        angularAnimate : {deps: ['angular']},  
        angularSanitize : {deps: ['angular']},  
        uiRouter : {deps: ['angular']},  
        ngResource: {deps: ['angular']},  
        ionic :  {deps: ['angular'], exports : 'ionic'},  
        ionicAngular: {deps: ['angular', 'ionic', 'uiRouter', 'angularAnimate', 'angularSanitize','ngResource']}  
    },  
    priority:['angular','ionic'],
    deps:['bootstrap']
});